Repository HarbourMasters/2ship2harkinian, pull requests merged in 2024-05, with the labels that each got.

#543 Fix macports cache
  .github/workflows/gtar
  .github/workflows/main.yml
  .github/workflows/pr-artifacts.yml
  CMake/DefaultCXX.cmake
  CMakeLists.txt
  mm/CMake/DefaultCXX.cmake
Labels: maintenance

#579 Display GC Version String On Title
  mm/src/overlays/gamestates/ovl_title/z_title.c
Labels: rom support

#498 Disabled checkbox fix
  mm/2s2h/BenGui/UIWidgets.cpp
Labels: bug, rika

#593 Fix crashing on non-portable builds
  mm/2s2h/SaveManager/SaveManager.cpp
Labels: rika

#611 Special char fix for dropped save files
  mm/2s2h/BenPort.cpp
Labels: rika

#608 Fix Skybox star colors
  mm/src/code/z_kankyo.c
Labels: rika

#612 Fix taking transformation mask off setting unexpected flags
  mm/src/overlays/actors/ovl_player_actor/z_player.c
Labels: rika

#592 Fix o2r file copy
  CMake/copy-existing-otrs.cmake
  CMakeLists.txt
Labels: rika

#588 ci(linux): install libzip without crypto, bump sdl from 2.28.5 -> 2.30.3
  .github/workflows/apt-deps.txt
  .github/workflows/main.yml
  CMake/Packaging.cmake
Labels: rika

#617 Fix play as kafei by swapping out resources later
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp
  mm/2s2h/Enhancements/GameInteractor/GameInteractor.h
  mm/2s2h/Enhancements/Graphics/PlayAsKafei.cpp
  mm/src/code/z_play.c
Labels: rika

#616 Tweaks to autosaves and pause saves to always persist them
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/Saving/SavingEnhancements.cpp
  mm/2s2h/Enhancements/Saving/SavingEnhancements.h
  mm/include/functions.h
  mm/src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
Labels: rika

#529 Fix GC Warning Labels
  mm/src/overlays/gamestates/ovl_file_choose/z_file_choose_NES.c
Labels: rom support, rika

#597 Display a MSAA value of 1x as "Off"
  mm/2s2h/BenGui/BenMenuBar.cpp
Labels: rika

#618 Fix issue where skipping clock tower cutscene would not return you correctly
  mm/2s2h/Enhancements/Cutscenes/StoryCutscenes/SkipClockTowerOpen.cpp
  mm/2s2h/Enhancements/GameInteractor/GameInteractor.h
  mm/src/overlays/actors/ovl_En_Test4/z_en_test4.c
Labels: rika

#622 Fix HUD editor position bugs
  mm/2s2h/BenGui/HudEditor.cpp
  mm/src/code/z_parameter.c
Labels: rika

#605 Adds sanity checks for bottle duping over items and prevents the issue causing Big Goron to not give the player the Keg License.
  mm/2s2h/Enhancements/Cheats/Infinite.cpp
Labels: rika
