Repository HarbourMasters/2ship2harkinian, pull requests merged in 2024-06, with the labels that each got.

#578 Fix Dpad Ocarina L Btn & GI Dpad Stuff
  mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp
  mm/2s2h/Enhancements/GameInteractor/GameInteractor.h
  mm/include/z64save.h
  mm/src/audio/code_8019AF00.c
  mm/src/overlays/actors/ovl_Arms_Hook/z_arms_hook.c
  mm/src/overlays/actors/ovl_Boss_02/z_boss_02.c
  mm/src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_mask.c
Labels: rika

#640 Fix the PRNG not being seeded when opening intro is skipped
  mm/src/overlays/gamestates/ovl_title/z_title.c
Labels: rika

#643 Add various tweaks and a warning to debug mode toggle
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/DeveloperTools/ActorViewer.cpp
  mm/2s2h/DeveloperTools/WarpPoint.cpp
  mm/src/code/z_scene.c
Labels: rika

#536 Add time-moves-when-you-move mode
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/Enhancements.cpp
  mm/2s2h/Enhancements/Enhancements.h
  mm/2s2h/Enhancements/Modes/TimeMovesWhenYouMove.cpp
  mm/2s2h/Enhancements/Modes/TimeMovesWhenYouMove.h
Labels: enhancement

#546 Skip Magic Arrow Equip Animation
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/Enhancements.cpp
  mm/2s2h/Enhancements/Enhancements.h
  mm/2s2h/Enhancements/Equipment/SkipMagicArrowEquip.cpp
  mm/2s2h/Enhancements/Equipment/SkipMagicArrowEquip.h
  mm/2s2h/Enhancements/GameInteractor/GameInteractor.cpp
  mm/2s2h/Enhancements/GameInteractor/GameInteractor.h
  mm/src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
Labels: enhancement

#585 Adds Dungeon Items to the Save Editor
  mm/2s2h/DeveloperTools/SaveEditor.cpp
  mm/include/z64save.h
Labels: enhancement

#590 [Graphics] Disable Black Bar Letterboxes
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/Enhancements.cpp
  mm/2s2h/Enhancements/Enhancements.h
  mm/2s2h/Enhancements/GameInteractor/GameInteractor.h
  mm/2s2h/Enhancements/Graphics/DisableBlackBars.cpp
  mm/2s2h/Enhancements/Graphics/DisableBlackBars.h
  mm/src/code/z_shrink_window.c
  mm/src/code/z_view.c
Labels: enhancement

#591 [Enhancement] Banker - Adds Min Max Functionality
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/Dialogue/Dialogue.h
  mm/2s2h/Enhancements/Dialogue/FastBankSelection.cpp
  mm/2s2h/Enhancements/Enhancements.cpp
  mm/2s2h/Enhancements/Enhancements.h
Labels: enhancement

#551 Add 2ship-specific BUILDING.md and supportedHashes.json.
  docs/BUILDING.md
  docs/supportedHashes.json
Labels: maintenance

#642 [Enhancement] Blast Mask with Powder Keg
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/Enhancements.cpp
  mm/2s2h/Enhancements/Enhancements.h
  mm/2s2h/Enhancements/Masks/BlastMaskKeg.cpp
  mm/2s2h/Enhancements/Masks/BlastMaskKeg.h
Labels: enhancement

#539 Add draw distance enhancements for actors and scene geometry
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/include/PR/gbi.h
  mm/src/code/z_actor.c
  mm/src/code/z_play.c
Labels: enhancement

#547 [Enhancement] Instant Putaway
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/Enhancements.cpp
  mm/2s2h/Enhancements/Enhancements.h
  mm/2s2h/Enhancements/GameInteractor/GameInteractor.h
  mm/2s2h/Enhancements/Player/ClimbSpeed.cpp
  mm/2s2h/Enhancements/Player/InstantPutaway.cpp
  mm/2s2h/Enhancements/Player/Player.h
  mm/2s2h/Enhancements/PlayerMovement/ClimbSpeed.h
  mm/src/overlays/actors/ovl_player_actor/z_player.c
Labels: enhancement

#548 [Cheat] Longer Deku Flower Gliding
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/Cheats/Cheats.h
  mm/2s2h/Enhancements/Cheats/LongerFlowerGlide.cpp
  mm/2s2h/Enhancements/Enhancements.cpp
  mm/2s2h/Enhancements/Enhancements.h
Labels: enhancement

#653 Fix Pause menu dungeon map palette loading
  mm/src/code/z_map_disp.c
Labels: rika

#549 [Enhancement] Fast Deku Flower Launch
  mm/2s2h/BenGui/BenMenuBar.cpp
  mm/2s2h/Enhancements/Enhancements.cpp
  mm/2s2h/Enhancements/Player/FastFlowerLaunch.cpp
  mm/2s2h/Enhancements/Player/Player.h
Labels: enhancement

#663 Add Free Look Camera Reset
  mm/2s2h/Enhancements/Camera/FreeLook.cpp
Labels: rika

#662 Fix Fast Text Not Working on Instant Textboxes
  mm/src/code/z_message.c
Labels: rika

#693 Fix for segfault when moon jump is activated on the day change
  mm/2s2h/Enhancements/Cheats/MoonJump.cpp
Labels: rika

#694 Fix: Add reset func for moon crash giants cutscene
  mm/src/overlays/actors/ovl_En_Fall/z_en_fall.c
Labels: rika

#710 Fix the check for preventing a HESS crash.
  mm/src/code/z_player_lib.c
  mm/src/code/z_skelanime.c
Labels: rika

#709 Save editor temple clear fix
  mm/2s2h/DeveloperTools/SaveEditor.cpp
Labels: rika

#664 Add Basic README
  README.md
  docs/poweredbylus.darkmode.png
  docs/poweredbylus.lightmode.png
  docs/supportedHashes.json
Labels: do not merge, rika

#718 Fix: Prevent Dawn Of screen crashing with 4th day glitch
  mm/src/overlays/gamestates/ovl_daytelop/z_daytelop.c
Labels: rika

#720 Fix: Prevent crash on loading OOB info panel textures in kaleido
  mm/src/overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope_NES.c
Labels: rika

#719 Fix: Handle reloading skybox textures
  mm/include/z64skybox.h
  mm/src/code/z_kankyo.c
  mm/src/code/z_vr_box.c
Labels: rika

#721 Tweak FreeLook camera reset logic
  mm/2s2h/Enhancements/Camera/FreeLook.cpp
Labels: rika

#722 Fix incorrect flag setting in save editor
  mm/2s2h/DeveloperTools/SaveEditor.cpp
Labels: rika

#724 Fix: Add reset func for EnBats actor
  mm/src/overlays/actors/ovl_En_Bat/z_en_bat.c
Labels: rika

#728 Fix: Clean up flags when using debug warp
  mm/src/overlays/gamestates/ovl_select/z_select.c
Labels: rika
